# Dockerfile.nginx
FROM nginx

# Install gettext for envsubst
RUN apt-get update && apt-get install -y gettext-base && rm -rf /var/lib/apt/lists/*

# Remove default NGINX configuration
RUN rm /etc/nginx/nginx.conf

# Copy the template and entrypoint script
COPY nginx.conf.template /etc/nginx/nginx.conf.template
COPY entrypoint.sh /entrypoint.sh

# Make sure the entrypoint script is executable
RUN chmod +x /entrypoint.sh

# Expose necessary ports
EXPOSE 80 443 1515 1514 55000

# Set the entrypoint
ENTRYPOINT ["/entrypoint.sh"]
