services:
  nginx:
    image: nginx
    container_name: hecate-dev
    volumes:
      - ./certs:/etc/nginx/certs:ro
    environment:
      - WEB_BACKEND_IP=${WEB_BACKEND_IP}             #--------------------------------------------------
      - WEB_BACKEND_PORT=${WEB_BACKEND_PORT}         # WEB: domain.com
      - WEB_SERVER_NAMES=${WEB_SERVER_NAMES}         #--------------------------------------------------

      - ELK_BACKEND_IP=${ELK_BACKEND_IP}             #--------------------------------------------------
      - ELK_BACKEND_PORT=${ELK_BACKEND_PORT}         # ELK STACK: elk.domain.com
      - ELK_SERVER_NAMES=${ELK_SERVER_NAMES}         #--------------------------------------------------

      - GRAFANA_BACKEND_IP=${GRAFANA_BACKEND_IP}             #--------------------------------------------------
      - GRAFANA_BACKEND_PORT=${GRAFANA_BACKEND_PORT}         # GRAFANA: grafana.domain.com
      - GRAFANA_SERVER_NAMES=${GRAFANA_SERVER_NAMES}         #--------------------------------------------------

      - JENKINS_BACKEND_IP=${JENKINS_BACKEND_IP}             #--------------------------------------------------
      - JENKINS_BACKEND_PORT=${JENKINS_BACKEND_PORT}         # JENKINS: jenkins.domain.com
      - JENKINS_SERVER_NAMES=${JENKINS_SERVER_NAMES}         #--------------------------------------------------

      - KEYCLOAK_BACKEND_IP=${KEYCLOAK_BACKEND_IP}             #--------------------------------------------------
      - KEYCLOAK_BACKEND_PORT=${KEYCLOAK_BACKEND_PORT}         # KEYCLOAK: iam.domain.com
      - KEYCLOAK_SERVER_NAMES=${KEYCLOAK_SERVER_NAMES}         #--------------------------------------------------

      - MATTERMOST_BACKEND_IP=${MATTERMOST_BACKEND_IP}             #--------------------------------------------------
      - MATTERMOST_BACKEND_PORT=${MATTERMOST_BACKEND_PORT}         # MATTERMOST: mattermost.domain.com
      - MATTERMOST_SERVER_NAMES=${MATTERMOST_SERVER_NAMES}         #--------------------------------------------------

      - NEBULA_BACKEND_IP=${NEBULA_BACKEND_IP}             #--------------------------------------------------
      - NEBULA_BACKEND_PORT=${NEBULA_BACKEND_PORT}         # NEBULA: nebula.domain.com
      - NEBULA_SERVER_NAMES=${NEBULA_SERVER_NAMES}         #--------------------------------------------------

      - NEXTCLOUD_BACKEND_IP=${NEXTCLOUD_BACKEND_IP}             #--------------------------------------------------
      - NEXTCLOUD_BACKEND_PORT=${NEXTCLOUD_BACKEND_PORT}         # NEXTCLOUD: nextcloud.domain.com
      - NEXTCLOUD_SERVER_NAMES=${NEXTCLOUD_SERVER_NAMES}         #--------------------------------------------------

      - OPENSTACK_BACKEND_IP=${OPENSTACK_BACKEND_IP}             #--------------------------------------------------
      - OPENSTACK_BACKEND_PORT=${OPENSTACK_BACKEND_PORT}         # OPENSTACK: oc.domain.com
      - OPENSTACK_SERVER_NAMES=${OPENSTACK_SERVER_NAMES}         #--------------------------------------------------
      
      - RESTIC_BACKEND_IP=${RESTIC_BACKEND_IP}             #--------------------------------------------------
      - RESTIC_BACKEND_PORT=${RESTIC_BACKEND_PORT}         # RESTIC: restic.domain.com
      - RESTIC_SERVER_NAMES=${RESTIC_SERVER_NAMES}         #--------------------------------------------------
      
      - SOC_BACKEND_IP=${SOC_BACKEND_IP}             #--------------------------------------------------
      - SOC_BACKEND_PORT=${SOC_BACKEND_PORT}         # SECURITY ONION: soc.domain.com
      - SOC_SERVER_NAMES=${SOC_SERVER_NAMES}         #--------------------------------------------------
      
      - WAZUH_BACKEND_IP=${WAZUH_BACKEND_IP}             #--------------------------------------------------
      - WAZUH_BACKEND_PORT=${WAZUH_BACKEND_PORT}         # WAZUH: wazuh.domain.com
      - WAZUH_SERVER_NAMES=${WAZUH_SERVER_NAMES}         #--------------------------------------------------
      
    ports:
      - "80:80"             #--------------------------------------------------
      - "443:443"           # WEB: domain.com
                            #--------------------------------------------------

      #- "EXT:INT"          #--------------------------------------------------
      #- "EXT:INT"          # ELK STACK: elk.domain.com
                            #--------------------------------------------------
                            
      #- "EXT:INT"          #--------------------------------------------------
      #- "EXT:INT"          # GRAFANA: grafana.domain.com
                            #--------------------------------------------------

      #- "EXT:INT"          #--------------------------------------------------
      #- "EXT:INT"          # JENKINS: jenkins.domain.com
                            #--------------------------------------------------
                        
      #- "EXT:INT"          #--------------------------------------------------
      #- "EXT:INT"          # KEYCLOAK: iam.domain.com
                            #--------------------------------------------------
                            
      #- "EXT:INT"          #--------------------------------------------------
      #- "EXT:INT"          # MATTERMOST: mattermost.domain.com
                            #--------------------------------------------------
                                                    
      #- "EXT:INT"          #--------------------------------------------------
      #- "EXT:INT"          # NEBULA: nebula.domain.com
                            #--------------------------------------------------
                        
      #- "EXT:INT"          #--------------------------------------------------
      #- "EXT:INT"          # NEXTCLOUD: nextcloud.domain.com
                            #--------------------------------------------------
                                                
      #- "EXT:INT"          #--------------------------------------------------
      #- "EXT:INT"          # OPENSTACK: oc.domain.com
                            #--------------------------------------------------
                            
      #- "EXT:INT"          #--------------------------------------------------
      #- "EXT:INT"          # RESTIC: restic.domain.com
                            #--------------------------------------------------
                            
      #- "EXT:INT"          #--------------------------------------------------
      #- "EXT:INT"          # SECURITY ONION: soc.domain.com
                            #--------------------------------------------------                    

      #- "1514:1514"        #--------------------------------------------------
      #- "1515:1515"        # WAZUH: wazuh.domain.com
                            #--------------------------------------------------
                        
      #- "EXT:INT"          #--------------------------------------------------
      #- "EXT:INT"          # EXAMPLE: example.domain.com
                            #--------------------------------------------------      
    entrypoint: >
    #--------------------------------------------------
    # WEB: domain.com
    #--------------------------------------------------
      sh -c "envsubst '\$BACKEND_IP \$BACKEND_PORT \$SERVER_NAMES' < /etc/nginx/nginx.conf.template > /etc/nginx/nginx.conf
      && nginx -g 'daemon off;'"

    #--------------------------------------------------
    # ELK STACK: elk.domain.com
    #--------------------------------------------------
      sh -c "envsubst '\$BACKEND_IP \$BACKEND_PORT \$SERVER_NAMES' < /etc/nginx/nginx.conf.template > /etc/nginx/nginx.conf
      && nginx -g 'daemon off;'"

    #--------------------------------------------------
    # ERPNEXT: erpnext.domain.com
    #--------------------------------------------------
      sh -c "envsubst '\$BACKEND_IP \$BACKEND_PORT \$SERVER_NAMES' < /etc/nginx/nginx.conf.template > /etc/nginx/nginx.conf
      && nginx -g 'daemon off;'"

    #--------------------------------------------------
    # GRAFANA: grafana.domain.com
    #--------------------------------------------------
      sh -c "envsubst '\$BACKEND_IP \$BACKEND_PORT \$SERVER_NAMES' < /etc/nginx/nginx.conf.template > /etc/nginx/nginx.conf
      && nginx -g 'daemon off;'"

    #--------------------------------------------------
    # JENKINS: jenkins.domain.com
    #--------------------------------------------------
      sh -c "envsubst '\$BACKEND_IP \$BACKEND_PORT \$SERVER_NAMES' < /etc/nginx/nginx.conf.template > /etc/nginx/nginx.conf
      && nginx -g 'daemon off;'"

    #--------------------------------------------------
    # KEYCLOAK: keycloak.domain.com
    #--------------------------------------------------
      sh -c "envsubst '\$BACKEND_IP \$BACKEND_PORT \$SERVER_NAMES' < /etc/nginx/nginx.conf.template > /etc/nginx/nginx.conf
      && nginx -g 'daemon off;'"

    #--------------------------------------------------
    # MAILCOW WEB UI: mail.domain.com
    #--------------------------------------------------
      sh -c "envsubst '\$BACKEND_IP \$BACKEND_PORT \$SERVER_NAMES' < /etc/nginx/nginx.conf.template > /etc/nginx/nginx.conf
      && nginx -g 'daemon off;'"

    #--------------------------------------------------
    # MATTERMOST: mattermost.domain.com
    #--------------------------------------------------
      sh -c "envsubst '\$BACKEND_IP \$BACKEND_PORT \$SERVER_NAMES' < /etc/nginx/nginx.conf.template > /etc/nginx/nginx.conf
      && nginx -g 'daemon off;'"

    #--------------------------------------------------
    # NEBULA: nebula.domain.com
    #--------------------------------------------------
      sh -c "envsubst '\$BACKEND_IP \$BACKEND_PORT \$SERVER_NAMES' < /etc/nginx/nginx.conf.template > /etc/nginx/nginx.conf
      && nginx -g 'daemon off;'"

    #--------------------------------------------------
    # NEXTCLOUD: nextcloud.domain.com
    #--------------------------------------------------
      sh -c "envsubst '\$BACKEND_IP \$BACKEND_PORT \$SERVER_NAMES' < /etc/nginx/nginx.conf.template > /etc/nginx/nginx.conf
      && nginx -g 'daemon off;'"

    #--------------------------------------------------
    # OPENSTACK: oc.domain.com
    #--------------------------------------------------
      sh -c "envsubst '\$BACKEND_IP \$BACKEND_PORT \$SERVER_NAMES' < /etc/nginx/nginx.conf.template > /etc/nginx/nginx.conf
      && nginx -g 'daemon off;'"

    #--------------------------------------------------
    # RESTIC: restic.domain.com
    #--------------------------------------------------
      sh -c "envsubst '\$BACKEND_IP \$BACKEND_PORT \$SERVER_NAMES' < /etc/nginx/nginx.conf.template > /etc/nginx/nginx.conf
      && nginx -g 'daemon off;'"

    #--------------------------------------------------
    # SECURITY ONION: soc.domain.com
    #--------------------------------------------------
      sh -c "envsubst '\$BACKEND_IP \$BACKEND_PORT \$SERVER_NAMES' < /etc/nginx/nginx.conf.template > /etc/nginx/nginx.conf
      && nginx -g 'daemon off;'"

    #--------------------------------------------------
    # WAZUH: wazuh.domain.com
    #--------------------------------------------------
      # sh -c "envsubst '\$BACKEND_IP \$BACKEND_PORT \$SERVER_NAMES' < /etc/nginx/nginx.conf.template > /etc/nginx/nginx.conf
      # && nginx -g 'daemon off;'"
      
    restart: always
