services:
  nginx:
    image: nginx:alpine
    container_name: hecate-dev
    volumes:
      - ./nginx.conf.template:/etc/nginx/nginx.conf.template:ro  # Template with placeholders
      - ./certs:/etc/nginx/certs:ro                           # SSL certificates
      - ./generate-nginx-conf.sh:/generate-nginx-conf.sh:ro  # Replacement script
    ports:
      - "80:80"
      - "443:443"
      - "1515:1515"    # Wazuh API
      - "1514:1514"    # Additional Wazuh ports
      - "55000:55000"  # Wazuh API HTTPS
    restart: always
    env_file:
      - .env
    entrypoint: /bin/sh -c "/generate-nginx-conf.sh && nginx -g 'daemon off;'"
