services:
  nginx:
    image: nginx
    container_name: hecate-dev
    volumes:
      - ./certs:/etc/nginx/certs:ro
    environment:
      - BACKEND_IP=${BACKEND_IP}
      - BACKEND_PORT=${BACKEND_PORT}
      - SERVER_NAMES=${SERVER_NAMES}
    ports:
      - "80:80"
      - "443:443"
      #- "1514:1514"        #--------------------------------------------------
      #- "1515:1515"        # Uncomment for Wazuh
                            #--------------------------------------------------

      #- "EXT:INT"          #--------------------------------------------------
      #- "EXT:INT"          # 4) MATTERMOST: mattermost.domain.com
                            #--------------------------------------------------
                        
      #- "EXT:INT"          #--------------------------------------------------
      #- "EXT:INT"          # 5) NEXTCLOUD: nextcloud.domain.com
                            #--------------------------------------------------
                        
      #- "EXT:INT"          #--------------------------------------------------
      #- "EXT:INT"          # 6) JENKINS: jenkins.domain.com
                            #--------------------------------------------------
                        
      #- "EXT:INT"          #--------------------------------------------------
      #- "EXT:INT"          # 7) GRAFANA: grafana.domain.com
                            #--------------------------------------------------
                        
      #- "EXT:INT"          #--------------------------------------------------
      #- "EXT:INT"          # 8) ELK STACK: elk.domain.com
                            #--------------------------------------------------
                        
      #- "EXT:INT"          #--------------------------------------------------
      #- "EXT:INT"          # 9) OPENSTACK: oc.domain.com
                            #--------------------------------------------------
                        
      #- "EXT:INT"          #--------------------------------------------------
      #- "EXT:INT"          # 10) NEBULA: nebula.domain.com
                            #--------------------------------------------------
                        
      #- "EXT:INT"          #--------------------------------------------------
      #- "EXT:INT"          # 11) SECURITY ONION: soc.domain.com
                            #--------------------------------------------------
                        
      #- "EXT:INT"          #--------------------------------------------------
      #- "EXT:INT"          # 12) RESTIC: restic.domain.com
                            #--------------------------------------------------
                        
      #- "EXT:INT"          #--------------------------------------------------
      #- "EXT:INT"          # 13) KEYCLOAK: iam.domain.com
                            #--------------------------------------------------
                        
      #- "EXT:INT"          #--------------------------------------------------
      #- "EXT:INT"          # 123) EXAMPLE: example.domain.com
                            #--------------------------------------------------      
    entrypoint: >
      sh -c "envsubst '\$BACKEND_IP \$BACKEND_PORT \$SERVER_NAMES' < /etc/nginx/nginx.conf.template > /etc/nginx/nginx.conf
      && nginx -g 'daemon off;'"
    restart: always
