services:
  nginx:
    image: nginx
    container_name: hecate-dev
    volumes:
      - ./certs:/etc/nginx/certs:ro
    environment:
      - BACKEND_IP=${BACKEND_IP}
      - BACKEND_PORT=${BACKEND_PORT}
      - SERVER_NAMES=${SERVER_NAMES}
    ports:
      - "80:80"
      - "443:443"
    entrypoint: >
      sh -c "envsubst '\$BACKEND_IP \$BACKEND_PORT \$SERVER_NAMES' < /etc/nginx/nginx.conf.template > /etc/nginx/nginx.conf
      && nginx -g 'daemon off;'"
    restart: always
