# docker-compose.yaml
services:
  nginx:
    image: nginx
    container_name: hecate-dev
    volumes:
      - ./:/usr/share/nginx/html:ro # Shared webroot for validation
      - ./nginx.conf:/etc/nginx/nginx.conf:ro # Custom NGINX configuration
      #- ./certs:/etc/nginx/certs:ro  # SSL certificates
    ports:
      - "80:8080"
      - "443:8443"
    restart: always
