# docker-compose.yaml
services:
  nginx:
    image: nginx
    container_name: hecate
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro # Custom NGINX configuration
      - ./certs:/etc/nginx/certs:ro  # SSL certificates
      - ./error_pages:/usr/share/nginx/html:ro
      - ./snippets:/etc/nginx/snippets:ro
      - ./conf.d:/etc/nginx/conf.d:ro
    ports:
      - "80:80"
      - "443:443"
      ##############################################################
      #- "1515:1515"   # <- uncomment if using Wazuh behind Hecate
      #- "1514:1514"   # <-
      #- "55000:55000" # <-
      ##############################################################
      #- "25:25"       # <- uncomment if using Mailcow behind Hecate
      #- "587:587"     # <-
      #- "465:465"     # <-
      #- "110:110"     # <-
      #- "995:995"     # <-
      #- "143:143"     # <-
      #- "993:993"     # <-
      ##############################################################
    restart: always
