# docker-compose.yaml
services:
  nginx:
    image: nginx
    container_name: hecate-sh
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro # Custom NGINX configuration
      - ./certs:/etc/nginx/certs:ro  # SSL certificates
    ports:
      - "80:80"
      - "443:443"
      #- "1515:1515"    # <- uncomment if using Wazuh behind proxy # Wazuh API
      #- "1514:1514"    # <- # Additional Wazuh ports
      #- "55000:55000"  # <- # Wazuh API HTTPS
      - "25:25"
      - "587:587"
      - "465:465"
      - "110:110"
      - "995:995"
      - "143:143"
      - "993:993"
    restart: always
