# docker-compose.yaml
services:
  nginx:
    image: nginx
    container_name: hecate-prod
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro # Custom NGINX configuration
      - ./certs:/etc/nginx/certs:ro  # SSL certificates
    ports:
      - "80:80"
      - "443:443"
      #- "1515:1515" # uncomment if setting up wazuh
      #- "1514:1514" # uncomment if setting up wazuh
    restart: always
